#!/bin/bash

mac=${1}


if [[ `echo ${mac} | egrep "^([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}$|^([0-9a-fA-F]{2}-){5}[0-9a-fA-F]{2}$"` ]]; then
	mac=`echo ${mac} | sed 's/:/%3A/'`
	search=`curl -s http://www.networkcenter.info/inform/mac?addr=${mac}`
	echo ${search} | awk -F "<p>" {'print $6'} | awk -F ":" {'print $2'} | awk -F "<" {'print $1'} | sed 's/^[ \t]*//'

else
	echo -e "
---------------------------------------------------------------------------------
Error input mac address!
Please enter in format:
00-aa-00-aa-00-0a or 00-AA-00-AA-00-0A or 00:aa:00:aa:00:0a or 00:AA:00:AA:00:0A
---------------------------------------------------------------------------------
"
fi